# Generated by Django 4.1.7 on 2023-07-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=1024)),
                ('data', models.TextField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_destination', to='main.warehouse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_source', to='main.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=512)),
                ('customer_phone', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_source', to='main.warehouse')),
            ],
        ),
    ]
