# Generated by Django 4.1.7 on 2023-07-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('traffic', '0002_agentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentorder',
            name='product',
        ),
        migrations.AddField(
            model_name='agentorder',
            name='product_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
            preserve_default=False,
        ),
    ]
