# Generated by Django 4.1.7 on 2023-07-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_remove_agentorder_product_agentorder_product_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentorder',
            old_name='customer',
            new_name='supplier',
        ),
    ]
